<script lang="ts">
  import {Meta, Story} from "@storybook/addon-svelte-csf";
  import {DbClient, MemoryAdapter, type InsertFact} from "@repo/facts-db";
  import ComposerModal from "./ComposerModal.svelte";

  const db = new DbClient(table => new MemoryAdapter(table));
  const emptyDb = new DbClient(table => new MemoryAdapter(table));

  const seed: InsertFact[] = [
    {
      content: "The quick brown fox jumps over the lazy dog",
    },
    {
      content: "Started from the bottom now we're here",
    },
    {
      content:
        "This is a really long paragraph generated by Code Pilot. It's a great tool for generating random text. All you have to do is type 'lorem' followed by the number of words you want to generate. For example, 'lorem 10' will generate a 10-word paragraph of lorem ipsum text. You can also generate a paragraph of random text by typing 'random' followed by the number of words you want to generate. For example, 'random 10' will generate a 10-word paragraph of random text. Code Pilot is a great tool for generating random text. It's easy to use and it's free!",
    },
  ];

  for (const fact of seed) {
    db.facts.add(fact);
  }
</script>

<Meta
  autodocs
  title="features/ComposerModal"
  component={ComposerModal}
  tags={["autodocs"]}
  parameters={{layout: "centered"}}
/>

<Story
  id="Composer"
  name="ComposerModal"
  let:args
>
  <textarea value="Open Composer" />
  <ComposerModal {...args} {db} />
</Story>

<Story
  id="EmptyComposer"
  name="Empty Composer Modal"
  let:args
>
  <textarea value="Open Composer" />
  <ComposerModal {...args} db={emptyDb} />
</Story>
