import FactListItem from "./FactListItem.svelte";
import type {Fact} from "@repo/facts-db";
import type {Meta, StoryObj} from "@storybook/svelte";

const meta: Meta<FactListItem> = {
  title: "features/FactListItem",
  component: FactListItem,
};

export default meta;

type Story = StoryObj<FactListItem>;

const fact: Fact = {
  id: 1,
  content:
    "This is a really long paragraph generated by Code Pilot. It's a great tool for generating random text. All you have to do is type 'lorem' followed by the number of words you want to generate. For example, 'lorem 10' will generate a 10-word paragraph of lorem ipsum text. You can also generate a paragraph of random text by typing 'random' followed by the number of words you want to generate. For example, 'random 10' will generate a 10-word paragraph of random text. Code Pilot is a great tool for generating random text. It's easy to use and it's free!",
};

export const Default: Story = {
  render: args => ({
    Component: FactListItem,
    props: args,
  }),
  args: {
    fact,
  },
};
