import {dummyCollection} from "./trpc";
import {
  InsertFactSchema,
  InsertLabelSchema,
} from "@repo/collection-service-defs";

export const labels: InsertLabelSchema[] = [
  {name: "ChatGPT"},
  {name: "OpenAI"},
  {name: "WorkExp"},
  {name: "Education"},
  {name: "Projects"},
  {name: "Skills"},
];

export const factsData: InsertFactSchema[] = [
  {
    content: "The quick brown fox jumps over the lazy dog",
    labels: [
      {name: "ChatGPT", _id: "1"},
      {name: "OpenAI", _id: "2"},
    ],
  },
  {
    content: "Started from the bottom now we're here",
    labels: [
      {name: "WorkExp", _id: "3"},
      {name: "Education", _id: "4"},
    ],
  },
  {
    content:
      "This is a really long paragraph generated by Code Pilot. It's a great tool for generating random text. All you have to do is type 'lorem' followed by the number of words you want to generate. For example, 'lorem 10' will generate a 10-word paragraph of lorem ipsum text. You can also generate a paragraph of random text by typing 'random' followed by the number of words you want to generate. For example, 'random 10' will generate a 10-word paragraph of random text. Code Pilot is a great tool for generating random text. It's easy to use and it's free!",
    labels: [
      {name: "Projects", _id: "5"},
      {name: "Skills", _id: "6"},
    ],
  },
  {
    content: "Hold the door",
    labels: [
      {name: "ChatGPT", _id: "1"},
      {name: "OpenAI", _id: "2"},
    ],
  },
  {
    content: "Winter is coming!",
    labels: [
      {name: "ChatGPT", _id: "1"},
      {name: "OpenAI", _id: "2"},
    ],
  },
  {
    content: "You know nothing, Jon Snow",
    labels: [],
  },
  {
    content: "A Lannister always pays his debts",
    labels: [],
  },
  {
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    labels: [],
  },
  {
    content:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    labels: [
      {name: "ChatGPT", _id: "1"},
      {name: "OpenAI", _id: "2"},
    ],
  },
  {
    content:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    labels: [],
  },
  {
    content:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    labels: [],
  },
  {
    content:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    labels: [],
  },
];

// eslint-disable-next-line complexity
export const seedDb = (interLabels: InsertLabelSchema[] = labels) => {
  for (const label of interLabels) {
    dummyCollection.labels.create.mutate(label);
  }

  for (const fact of factsData) {
    dummyCollection.facts.create.mutate(fact);
  }
};
