import type {Meta, StoryObj} from "@storybook/react";
import {FactCards} from "./FactCards";
import {Fact} from "@repo/facts-db";

const meta = {
  title: "features/collection/components/FactCards",
  component: FactCards,
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof FactCards>;

export default meta;
type Story = StoryObj<typeof meta>;

const facts: Fact[] = [
  {
    id: 1,
    content: "The quick brown fox jumps over the lazy dog",
    labels: [
      {
        id: 1,
        name: "ChatGPT",
      },
      {
        id: 2,
        name: "OpenAI",
      },
    ],
  },
  {
    id: 2,
    content: "Started from the bottom now we're here",
    labels: [
      {
        id: 3,
        name: "WorkExp",
      },
      {
        id: 4,
        name: "Education",
      },
    ],
  },
  {
    id: 3,
    content:
      "This is a really long paragraph generated by Code Pilot. It's a great tool for generating random text. All you have to do is type 'lorem' followed by the number of words you want to generate. For example, 'lorem 10' will generate a 10-word paragraph of lorem ipsum text. You can also generate a paragraph of random text by typing 'random' followed by the number of words you want to generate. For example, 'random 10' will generate a 10-word paragraph of random text. Code Pilot is a great tool for generating random text. It's easy to use and it's free!",
    labels: [
      {
        id: 5,
        name: "Projects",
      },
      {
        id: 6,
        name: "Skills",
      },
    ],
  },
  {
    id: 4,
    content: "Hold the door",
    labels: [
      {
        id: 1,
        name: "ChatGPT",
      },
      {
        id: 3,
        name: "OpenAI",
      },
    ],
  },
  {
    id: 5,
    content: "Winter is coming!",
    labels: [],
  },
];

export const Default: Story = {
  args: {
    facts,
  },
};

export const Highlighted: Story = {
  args: {
    facts,
    highlightedFacts: [facts[0], facts[3]],
  },
};

export const HighlightedLabels: Story = {
  args: {
    facts,
    highlightedFacts: [facts[0]],
    highlightedLabels: [facts[0].labels[0], facts[1].labels[1]],
  },
};
